# Generated by Django 3.2.4 on 2021-06-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_art',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
